### ISSUE TITLE
Numbering and Lettering

### ISSUE THREAD

**Issue by tspier** [neunenak/typst-leipzig-glossing#4]
Is it possible to use numbers and letters that align as in the picture attached?

![example](https://github.com/neunenak/typst-leipzig-glossing/assets/69118319/8085c712-b1f0-486c-9f33-0075ae15ec58)

**Comment by betoma** [comment]
Currently working on some changes to improve flexibility wrt numbering and spacing for glosses, hopefully I'll be able to put in a PR soon!

**Comment by rwmpelstilzchen** [comment]
And references! This goes hand in hand with numbering of examples and sub-examples. [ExPex](https://ctan.org/pkg/expex) handles this beautifully.

**Comment by neunenak** [comment]
Somehow I missed the notification for this issue - I'll look into this, although I may not get to it soon.

**Comment by neunenak** [comment]
I've merged @rwmpelstilzchen 's PR (with some tweaks) that implements adding references to glosses. Implementing a more sophisticated way of assigning letters/numbers to glosses is work remaining to be done. I may or may not get around to this in the near future, and I'm definitely happy to accept more PRs for this functionality.
