### ISSUE TITLE
Mirror the canonical repository

### ISSUE THREAD

**Issue by rwmpelstilzchen** [neunenak/typst-leipzig-glossing#5]
According to the [readme](https://github.com/neunenak/typst-leipzig-glossing/blob/master/README.md), the current repository is a mirror of [this one](https://code.everydayimshuflin.com/greg/typst-lepizig-glossing/). It seems the canonical repository is two commits ahead: its head is [`3882f4e791`](https://code.everydayimshuflin.com/greg/typst-lepizig-glossing/commit/3882f4e791f6b5a6e3088ca0a415e7695160fe3a); no major changes though. Isn’t the process automated?

**Comment by neunenak** [comment]
Pushed this Github repo to the latest `master`. This is not an automated process right now.

To be honest, I don't really like Github and I don't want to use it as even a secondary repository for my code. Unfortunately, Github currently has strong network effects, and there isn't currently another convenient way for me to accept pull requests from other people. This is a problem I'd like to solve somehow.

**Comment by rwmpelstilzchen** [comment]
I share your dislike of GitHub… I’d happily contribute through your Gitea instance directly, but I cannot create an account there: there is only a ‘Sign In’ button, no ‘Sign Up’. Perhaps I am missing something, but can one make a pull request without having an account on the same instance? And if it is possible, wouldn’t it be still impossible to take part in discussions, open issues, etc.?

Perhaps consider making signing up possible (with manual approval maybe, so people don’t just upload their own projects there or create spam accounts).
